template: 'templates/client_template.py.mako'
clientType: mujinvision
templateArgs:  # Strings are added to client_template.py.mako
  clientTaskName: binpicking
  parentClassFile: VisionControllerClient
  parentClassName: VisionControllerClient
  extraSuperConstructorArgs: ''
  extraConstructorArgs: ''
  extraConstructorArgsDocstringLines: ""
  extraConstructorContent: ""
  extraClientContent: ""
  extraClientStaticFunctions: ""
  clientContent: ""
generatorSettingsComponents:
  timeout:
    default: 3000.0
    description: Time in seconds after which the command is assumed to have failed.
    type: number
    x-doNotAddToPayload: true  # Used only inside the client, not sent to the server
  ignoredArgsParam:
    ignoredArgs:
      description: These arguments may be passed to the method, but are ignored.
include:
- components.yaml
x-specModifications:
  services:
    # GetPublishedState:
    #   TODO_CONFIRM_BACKEND: ''
    GetPublishedStateService:
      TODO_CONFIRM_BACKEND: ''
      serversideCommandName: GetPublishedState
      parameters:
        timeout:
            paramOrderingIndex: 0
            $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
    Ping:
      TODO_CONFIRM_BACKEND: ''
      parameters:
        timeout:
            paramOrderingIndex: 0
            $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
    SetLogLevel:
      TODO_CONFIRM_BACKEND: ''
      parameters:
        componentLevels:
          paramOrderingIndex: 0
        timeout:
          paramOrderingIndex: 1
          $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
    Cancel:
      TODO_CONFIRM_BACKEND: ''
      x-methodStartSetup: log.info('Canceling command...')
      x-omitRegularReturnStatement: true
      x-modifiedReturnStatement: |
        response = self._SendConfiguration(command, timeout=timeout)
        log.info('Command is stopped.')
        return response
      parameters:
        timeout:
          paramOrderingIndex: 0
          $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
    Quit:
      TODO_CONFIRM_BACKEND: ''
      x-methodStartSetup: log.info('Stopping visionserver...')
      x-omitRegularReturnStatement: true
      x-modifiedReturnStatement: |
        response = self._SendConfiguration(command, timeout=timeout)
        log.info('Visionserver is stopped.')
        return response
      parameters:
        timeout:
          paramOrderingIndex: 0
          $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
    GetTaskStateService:
      TODO_CONFIRM_BACKEND: ''
      serversideCommandName: GetTaskState
      parameters:
        taskId:
          paramOrderingIndex: 0
        cycleIndex:
          paramOrderingIndex: 1
        taskType:
          paramOrderingIndex: 2
        timeout:
          paramOrderingIndex: 3
          $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
    GetVisionStatistics:
      TODO_CONFIRM_BACKEND: ''
      parameters:
        cycleIndex:
          paramOrderingIndex: 1
        taskId:
          paramOrderingIndex: 0
        timeout:
          paramOrderingIndex: 3
          $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
        taskType:
          paramOrderingIndex: 2
    GetLatestDetectedObjects:
      TODO_CONFIRM_BACKEND: ''
      parameters:
        cycleIndex:
          paramOrderingIndex: 1
        taskId:
          paramOrderingIndex: 0
        timeout:
          paramOrderingIndex: 3
          $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
        taskType:
          paramOrderingIndex: 2
    GetLatestDetectionResultImages:
      TODO_CONFIRM_BACKEND: ''
      x-methodStartSetup: log.verbose("Getting latest detection result images...")
      x-omitRegularReturnStatement: true
      x-modifiedReturnStatement: return self._ExecuteCommand(command, timeout=timeout, recvjson=False, blockwait=blockwait)
      parameters:
        newerthantimestamp:
          paramOrderingIndex: 3
          default: 0
          isRequired: true
        metadataOnly:
          paramOrderingIndex: 5
          default: false
        sensorSelectionInfos:
          paramOrderingIndex: 4
        timeout:
          paramOrderingIndex: 9
          $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
        taskId:
          paramOrderingIndex: 0
        taskType:
          paramOrderingIndex: 2
        cycleIndex:
          paramOrderingIndex: 1
        imagesTypes:
          paramOrderingIndex: 6
        limit:
          paramOrderingIndex: 7
        blockwait:
          paramOrderingIndex: 8
          default: true
          x-doNotAddToPayload: true
    GetDetectionHistory:
      TODO_CONFIRM_BACKEND: ''
      x-methodStartSetup: log.verbose("Getting detection result at %r ...", timestamp)
      x-omitRegularReturnStatement: true
      x-modifiedReturnStatement: return self._ExecuteCommand(command, timeout=timeout, recvjson=False)
      parameters:
        timestamp:
          paramOrderingIndex: 0
        timeout:
          paramOrderingIndex: 1
          $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
    BackupVisionLog:
      TODO_CONFIRM_BACKEND: ''
      serversideCommandName: BackupDetectionLogs
      parameters:
        cycleIndex:
          paramOrderingIndex: 0
        sensorTimestamps:
          paramOrderingIndex: 1
        fireandforget:
          paramOrderingIndex: 2
          default: false
          $merge: '#/components/Internal_ExecuteCommandParameters/fireandforget'
        timeout:
          paramOrderingIndex: 3
          default: 2.0
          $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
    StopTask:
      TODO_CONFIRM_BACKEND: ''
      x-methodStartSetup: log.verbose('Stopping detection thread...')
      parameters:
        timeout:
          paramOrderingIndex: 8
          $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
        taskTypes:
          paramOrderingIndex: 3
        waitForStop:
          paramOrderingIndex: 5
          default: true
          isRequired: true
        removeTask:
          paramOrderingIndex: 6
          default: false
          isRequired: true
        taskId:
          paramOrderingIndex: 0
        taskType:
          paramOrderingIndex: 2
        fireandforget:
          $merge: '#/components/Internal_ExecuteCommandParameters/fireandforget'
          paramOrderingIndex: 7
        cycleIndex:
          paramOrderingIndex: 4
        taskIds:
          paramOrderingIndex: 1
    ResumeTask:
      TODO_CONFIRM_BACKEND: ''
      x-methodStartSetup: log.verbose('Resuming detection thread...')
      parameters:
        timeout:
          paramOrderingIndex: 7
          $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
        taskTypes:
          paramOrderingIndex: 3
        waitForStop:
          paramOrderingIndex: 5
        taskId:
          paramOrderingIndex: 0
        taskType:
          paramOrderingIndex: 2
        fireandforget:
          $merge: '#/components/Internal_ExecuteCommandParameters/fireandforget'
          paramOrderingIndex: 6
        cycleIndex:
          paramOrderingIndex: 4
        taskIds:
          paramOrderingIndex: 1
    StartObjectDetectionTask:
      TODO_CONFIRM_BACKEND: ''
      x-methodStartSetup: |
        log.verbose('Starting detection thread...')
        assert taskId is not None
      parameters:
        systemState:
          paramOrderingIndex: 2
        timeout:
          paramOrderingIndex: 3
          $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
        taskId:
          paramOrderingIndex: 0
        inputArgs:
          paramOrderingIndex: 1
      returns:
        dict:
          description: Returns immediately once the call completes
    StartContainerDetectionTask:
      TODO_CONFIRM_BACKEND: ''
      x-methodStartSetup: |
        log.verbose('Starting container detection thread...')
        assert taskId is not None
      parameters:
        systemState:
          paramOrderingIndex: 2
        timeout:
          paramOrderingIndex: 3
          $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
        taskId:
          paramOrderingIndex: 0
        inputArgs:
          paramOrderingIndex: 1
      returns:
        dict:
          description: Returns immediately once the call completes
    StartVisualizePointCloudTask:
      TODO_CONFIRM_BACKEND: ''
      x-methodStartSetup: log.verbose('Starting visualize pointcloud thread...')
      parameters:
        systemState:
          paramOrderingIndex: 1
        timeout:
          paramOrderingIndex: 2
          $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
        inputArgs:
          paramOrderingIndex: 0
      returns:
        dict:
          description: Returns immediately once the call completes